apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
    prometheus.io/path: "/metrics"
  name: trickster
spec:
  ports:
    - port: 9090
      targetPort: 9090
      name: metrics
  selector:
    name: trickster
